PREFIX=main
OUTPUT=taylorGreenVortex

${OUTPUT}-0: ${PREFIX}.c
	gcc -std=c99 -O0 -o "${OUTPUT}-0" ${PREFIX}.c

${OUTPUT}-1: ${PREFIX}.c
	gcc -std=c99 -O1 -o "${OUTPUT}-0" ${PREFIX}.c

${OUTPUT}-3: ${PREFIX}.c
	gcc -std=c99 -O3 -o "${OUTPUT}-0" ${PREFIX}.c

${OUTPUT}-fast: ${PREFIX}.c
	gcc -std=c99 -Ofast -o "${OUTPUT}-0" ${PREFIX}.c

